version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
  
  pre_build:
    commands:
      - echo "Starting build process at `date`"
      
  build:
    commands:
      - echo "Building static files..."
      - echo "Current directory contents:"
      - ls -la
      
  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: src
  discard-paths: false
  name: web-artifacts