version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  pre_build:
    commands:
      - echo "Starting build process..."
      
  build:
    commands:
      - echo "Building..."
      
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - src/**/*
  discard-paths: false