version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  build:
    commands:
      - echo "Building..."
      - ls -la
      - ls -la src/
      
artifacts:
  name: BuildArtifact
  files:
    - '**/*'
  base-directory: src