version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  build:
    commands:
      - echo "Preparing deployment files..."
      - cd src
      - ls -la
      
artifacts:
  files:
    - '**/*'
  base-directory: src