version: 0.2
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
  
  pre_build:
    commands:
      - echo "Starting build process at `date`"
      
  build:
    commands:
      - echo "Building static files..."
      - echo "Build started on `date`"
      
  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Build completed on `date`"
      - echo "Copying files to artifact directory..."
      - cp -r src/* .

artifacts:
  files:
    - '**/*'
  discard-paths: no