version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  pre_build:
    commands:
      - echo "Starting build process..."
      
  build:
    commands:
      - echo "Building..."
      - mkdir -p build
      - cp -r src/* build/
      
  post_build:
    commands:
      - echo "Build completed"
      - ls -la build/

artifacts:
  files:
    - '**/*'
  base-directory: build