version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  build:
    commands:
      - echo "Building..."
      
artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/**/*
  base-directory: .
  name: BuildArtifact