version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  pre_build:
    commands:
      - echo "Starting build process..."
      - pwd
      - ls -la
      
  build:
    commands:
      - echo "Building..."
      - ls -la src/
      
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  base-directory: src
  discard-paths: false